export const ONCHANGE = 'ONCHANGE'
export const SUBMIT ='SUBMIT'
export const USERS_LIST = 'USERS_LIST'
export const DELETE = 'DELETE'
export const EDIT = 'EDIT'
export const UPDATE = 'UPDATE'
export const RESET = 'RESET'
export const FATCHUSERID = 'FATCHUSERID'
// export const USERNAME = 'USERNAME'
// export const EMAIL = 'EMAIL'
// export const PASSWORd = 'PASSWORD'
// export const CONFORMPASSWORD = 'CONFORMPASSWORD'

